#!/bin/bash
#
# ./leabackup - restic backups, made easy 
#
# @version  0.1.0
# @date     2019-01-09
# @license  DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#set -x
startTime=`date +%s`

# path
location="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

enableLock="true"

source ${location}/kernel/menu.sh

source ${location}/kernel/header.sh

# do stuff before making any backup
for files in $(ls ${location}/pre-backup/); do
	include ${location}/pre-backup/$files 
done

startMinute=$(date +"%M")
startHour=$(date +"%H")

# backup specific repo
if [ "$aRepository" ]; then
    repository=$aRepository
    source ${location}/kernel/policies/policy.sh
fi 

# backup all repos
if [ -z "$aRepository" ]; then
    logme 'Backup started';
    for repository in $(ls ${location}/backups/); do
        # load repo config
        source ${location}/kernel/policies/policy.sh
    done
    logme 'Backup ended';
fi

# do stuff after the backups are done
for files in $(ls ${location}/post-backup/); do
	include ${location}/post-backup/$files 
done

source ${location}/kernel/footer.sh 
source ${location}/kernel/notifications.sh