#!/bin/bash
#
# ./leabackup - restic backups, made easy 
#
# @version  0.1.0
# @date     2019-01-09
# @license  DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#set -x
startTime=`date +%s`

# path
location="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

errorLogsFile=${location}/storage/logs/.error.${RANDOM:0:10}.log
touch $errorLogsFile;

source ${location}/kernel/header.sh

# do stuff before making any backup
for files in $(ls ${location}/pre-backup/); do
	include ${location}/pre-backup/$files 
done

startMinute=$(date +"%M")
startHour=$(date +"%H")

# backup specific repo
if [ ! -z "$1" ]; then
    envPath=${location}/backups/$1/.env;
    if [[ -f "$envPath" ]]; then
        repository=$1;
        source ${location}/kernel/policies/policy.sh
    else
        red "There is no backup named $1"
        exit;
    fi 
fi

# backup all repos
if [ -z "$1" ]; then
    logme 'Backup started';
    for repository in $(ls ${location}/backups/); do
        # load repo config
        source ${location}/kernel/policies/policy.sh
    done
    logme 'Backup ended';
fi


# do stuff after the backups are done
for files in $(ls ${location}/post-backup/); do
	include ${location}/post-backup/$files 
done


source ${location}/kernel/footer.sh 
source ${location}/kernel/notifications.sh