#!/bin/bash
#
# ./restback - restic backups, made easy 
#
# @version  0.1.0
# @date     2019-01-09
# @license  DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE

startTime=`date +%s`

# path
location="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
appname=$(basename "$0")

source ${location}/config.sh
source ${location}/kernel/header.sh

# do stuff before making any backup
for files in $(ls ${location}/pre-backup/); do
	include ${location}/pre-backup/$files
done

# backup specific repo
if [ ! -z "$1" ]; then
    config=${location}/backups/$1/config;
    if [[ -f "$config" ]]; then
        cat $config
    else
        red "There is no backup named $1"
    fi 
fi

# backup all repos
if [ -z "$1" ]; then
    echo 'Backup started';
    for repository in $(ls ${location}/backups/); do
        # load repo config
        include ${location}/backups/$repository/config

        for policy in $(ls ${location}/backups/$repository/policy/*);
        do 
            echo "Backing up $policy";
            include $policy
        done
    done
fi

# do stuff after the backups are done
for files in $(ls ${location}/post-backup/); do
	include ${location}/post-backup/$files
done

source ${location}/kernel/footer.sh
